-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 00:04:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbDataStreamHandler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbDataStreamHandler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbDataStreamHandler` DEFAULT CHARACTER SET utf8 ;
USE `dbDataStreamHandler` ;

-- -----------------------------------------------------
-- Table `dbDataStreamHandler`.`DataSensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbDataStreamHandler`.`DataSensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `equipmentId` VARCHAR(45) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `value` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
